"""
Remove pre- and suffixes from words.
"""

# Maps English to ipa to reduce accidental deletions
prefixes = {
'ab'    : ['æb'],
'ad'    : ['ʌd'],
'an'    : ['æn'],
'after' : ['æftɚ'],
'ante'  : ['æntɛ', 'æntɪ'],
'anti'  : ['æntɪ', 'æntʌ'],
'auto'  : ['ɔtʌ'],
'be'    : ['bɪ'],
'bi'    : ['baj'],
'circum': ['sɚkʌm'],
'co'    : ['kow'],
'com'   : ['kʌm'],
'con'   : ['kɑn'],
'contra': ['kɑntɹʌ', 'kɑntɹæ'],
'contro': ['kɑntɹʌ', 'kɑntɹow'],
'de'    : ['dɪ', 'di'],
'dis'   : ['dɪs'],
'en'    : ['ɛn', 'ɪn'],
'em'    : ['ɛm'],
'ex'    : ['ɪk', 'ɛk'],
'extra' : ['ɛkstɹʌ', 'ɛkstɹæ'],
'giga'  : ['gɪgʌ'],
'heter' : ['hɛtɚ'],
'hetero': ['hɛtɚʌ', 'hɛtɚow'],
'homo'  : ['howmow', 'hɔmʌ', 'howmʌ'],
'homeo' : ['howmiow'],
'hyper' : ['hajpɚ'],
'il'    : ['ɪl'],
'im'    : ['ɪm'],
'in'    : ['ɪn', 'ɪŋ'],
'ir'    : ['ɪɹ'],
'inter' : ['ɪntɚ'],
'intra' : ['ɪntɹʌ'],
'intro' : ['ɪntɹʌ', 'ɪˈntɹow'],
'kilo'  : ['kɪlɔ', 'kɪlʌ', 'kʌlɑ', 'kɪlʌ', 'kilow', 'kɪlow'],
'macro' : ['mækɹow'],
'magni' : ['mægnʌ'],
'mega'  : ['mɛgʌ'],
'micro' : ['majkɹow', 'majkɹʌ', 'majkɹɑ', 'majkɹɔ'],
'mid'   : ['mɪd'],
'milli' : ['mɪli', 'mɪlʌ', 'mɪlɪ'],
'mis'   : ['mɪs'],
'mono'  : ['mownow', 'mɑnʌ', 'mɑnɚ', 'mʌnɑ'],
'nano'  : ['nænow', 'nɑnow'],
'non'   : ['nɑn'],
'omni'  : ['ɑmni', 'ɑmnʌ'],
'over'  : ['owvɚ'],
'penta' : ['pɛntʌ', 'pɛntɪ', 'pɛnɪ', 'pɛntæ'],
'post'  : ['powst', 'pɑst'],
'pre'   : ['pɹɛ', 'pɹʌ', 'pɹɪ', 'pɹi'],
'pro'   : ['pɹow'],
'quad'  : ['kwɑd'],
're'    : ['ɹi', 'ɹɪ'],
'sub'   : ['sʌb'],
'super' : ['supɚ'],
'sym'   : ['sɪm', 'sʌm'],
'syn'   : ['sɪn'],
'tele'  : ['tili', 'tɛlʌ'],
'trans' : ['tɹænz'],
'tri'   : ['tɹaj'],
'un'    : ['ʌn'],
'uni'   : ['junɪ', 'junʌ', 'junʌ'],
'ultra' : ['ʌltɹʌ'],
'up'    : ['ʌp'],
}

# https://www.grammarbank.com/common-suffixes.html
suffixes = {
'\'d'    : ['d'],
'\'s'    : ['z', 's'],
'able'   : ['ʌbʌl'],
'ac'     : ['æk'],
'acy'    : ['ʌsi'],
'age'    : ['tʌʤ'],
'al'     : ['ʌl'],
'an'     : ['ʌn'],
'ana'    : ['ɑnʌ', 'ænʌ'],
'ance'   : ['ʌns'],
'ancy'   : ['ʌnsi'],
'ant'    : ['ʌnt'],
'ar'     : ['gɚ'],
'arium'  : ['ɛɹiʌm'],
'ary'    : ['ɛɹi', 'jɚi', 'ɚi'],
'ate'    : ['ejt', 'ʌt'],
'ation'  : ['ejʃʌn'],
'cle'    : ['kʌl'],
'cule'   : ['kjul'],
'culus'  : ['kjʌlʌs'],
'cy'     : ['si'],
'ed'     : ['d', 'ɚd', 'id', 'ʌd', 'ɪd'],
'ee'     : ['i'],
'eer'    : ['ɪɹ', 'iɹ'],
'el'     : ['ʌl'],
'en'     : ['ʌn'],
'ence'   : ['ʌns'],
'ency'   : ['ɪnsi', 'ʌnsi'],
'ent'    : ['ɛnsi'],
'er'     : ['ɚ'],
'esce'   : ['ɛs'],
'escent' : ['ɛsɪnt', 'ɛsʌnt'],
'escence': ['ɪsʌns', 'ɛsɪs', 'ɛsʌns'],
'esque'  : ['ʌsk', 'ɛsk'],
'ess'    : ['ʌs'],
'est'    : ['ʌst'],
'ette'   : ['ɛt'],
'eur'    : ['uɹ', 'ɚ'],
'fy'     : ['faj'],
'ial'    : ['ʌl'],
'ian'    : ['iʌn'],
'ible'   : ['ʌl'],
'ic'     : ['ɪk'],
'ical'   : ['ɪkʌl', 'ʌkʌl'],
'ice'    : ['ʌs', 'ɪs'],
'ier'    : ['ajɚ'],
'ies'    : ['ajz', 'iz'],
'ile'    : ['ʌl', 'ajʌl', 'ajl', 'ɪl'],
'ine'    : ['ʌn', 'in', 'ajn'],
'ing'    : ['ɪŋ'],
'ion'    : ['ʌn'],
'ish'    : ['ɪʃ'],
'ism'    : ['ɪzm', 'ɪzʌm'],
'ist'    : ['ɪst'],
'ite'    : ['ajt'],
'itis'   : ['ajˈtɪs', 'ajtʌs'],
'ive'    : ['ɪv'],
'ize'    : ['ajz'],
'ly'     : ['li'],
'ment'   : ['mɛnt', 'mʌnt'],
'mony'   : ['mʌni', 'mowni'],
'ness'   : ['nɛs', 'nɪs', 'nʌs'],
'oid'    : ['ɔjd'],
'or'     : ['ɚ'],
'orium'  : ['ɔɹiʌm'],
'ory'    : ['ɹi', 'ɚi', 'ɔɹi'],
'ose'    : ['ows'],
'osis'   : ['owsɪs', 'owsʌs'],
'ous'    : ['ʌs'],
'ry'     : ['ɚi', 'ɹi'],
's'      : ['z', 's'],
's\''    : ['z', 's'],
'tion'   : ['ʃʌn'],
'tude'   : ['tud'],
'ty'     : ['ti'],
'ure'    : ['ɚ'],
}
